--- 
default: 
  adapter: postgresql
  username: postgres
  password: 2211
  pool: "<%=  5 %>"
  timeout: 5000
development: 
  adapter: postgresql
  username: postgres
  password : 2211
  database: toy_app_development
  pool: "<%= 5  %>"
  timeout: 5000
production: 
  adapter: postgresql
  username: postgres
  password: 2211
  database: toy_app_production
  pool: "<%= 5  %>"
  timeout: 5000
test: 
  adapter: postgresql
  username: postgres
  password: 2211
  database: toy_app_test
  pool: "<%= 5  %>"
  timeout: 5000
